### ISSUE TITLE
About archived device tree land

### ISSUE THREAD

**Issue by arizaini** [nichcream/android_kernel_xiaomi_msm8937#3]
@nichcream are you stop supporting redmi 3s sir?... And i want to know is there any way to standalone compile both libshim? Or are u still have already compiled latest libshim_cameraservice.so and libshim_pthreads.so sir? If u not bother can u send it to me? For testing camera on P DP5 i checking on output log it's mention mm-camera-daemon crashes mention pthread to, i just wanna test is that can be fixed with the both library compiled on oreo, thank you

**Comment by nichcream** [comment]
You'll need to do something like this on generic system images, since shimming is a linker extension which AOSP does not have. https://github.com/nichcream/android_device_xiaomi_land/commit/4ebe6394177612426daef6035041040adf50841a#diff-010b5f00e9fd0fd514473580a658089dR725

And yes, I'll be taking my leave from development for a while, and since the trees are relatively stable now.
